// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Persistence;

#nullable disable

namespace Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250723105451_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.AboutMe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GitHub")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LinkedIn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProfilePictureUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("AboutMe");
                });

            modelBuilder.Entity("Domain.AboutMe", b =>
                {
                    b.OwnsOne("Domain.LocalizedString", "Bio", b1 =>
                        {
                            b1.Property<int>("AboutMeId")
                                .HasColumnType("int");

                            b1.Property<string>("En")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("He")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("AboutMeId");

                            b1.ToTable("AboutMe");

                            b1.WithOwner()
                                .HasForeignKey("AboutMeId");
                        });

                    b.OwnsOne("Domain.LocalizedString", "FullName", b1 =>
                        {
                            b1.Property<int>("AboutMeId")
                                .HasColumnType("int");

                            b1.Property<string>("En")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("He")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("AboutMeId");

                            b1.ToTable("AboutMe");

                            b1.WithOwner()
                                .HasForeignKey("AboutMeId");
                        });

                    b.OwnsOne("Domain.LocalizedString", "Location", b1 =>
                        {
                            b1.Property<int>("AboutMeId")
                                .HasColumnType("int");

                            b1.Property<string>("En")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("He")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("AboutMeId");

                            b1.ToTable("AboutMe");

                            b1.WithOwner()
                                .HasForeignKey("AboutMeId");
                        });

                    b.Navigation("Bio")
                        .IsRequired();

                    b.Navigation("FullName")
                        .IsRequired();

                    b.Navigation("Location")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
